'use strict';

/* Controllers */

function KegListController($scope) {
	$scope.kegs = [
		{ "name": "Beer Name",
		  "longName": "Long Beer NAME",
		  "style": "A Beer Style",
		  "brewery": "Moorehouse Brewery",
		  "url": "http://vandermore.com",
		  "abv": "0",
		  "ibu": "0",
		  "srm_lovibond": "5",
		  "status": "0" },
		{ "name": "Beer Name 2",
		  "longName": "Long Beer NAME",
		  "style": "A Beer Style",
		  "brewery": "Moorehouse Brewery",
                  "url": "http://vandermore.com",
		  "abv": "0",
		  "ibu": "0",
		  "srm_lovibond": "5",
		  "status": "0" },
		{ "name": "Beer Name 3",
		  "longName": "Long Beer NAME",
		  "style": "A Beer Style",
		  "brewery": "Moorehouse Brewery",
                  "url": "http://vandermore.com",
		  "abv": "0",
		  "ibu": "0",
		  "srm_lovibond": "5",
		  "status": "0" },
		{ "name": "Beer Name 4",
		  "longName": "Long Beer NAME",
		  "style": "A Beer Style",
		  "brewery": "Moorehouse Brewery",
                  "url": "http://vandermore.com",
		  "abv": "0",
		  "ibu": "0",
		  "srm_lovibond": "5",
		  "status": "0" },
		{ "name": "Beer Name 5",
		  "longName": "Long Beer NAME",
		  "style": "A Beer Style",
		  "brewery": "Moorehouse Brewery",
                  "url": "http://vandermore.com",
		  "abv": "0",
		  "ibu": "0",
		  "srm_lovibond": "5",
		  "status": "0" }
	];
}
